### ISSUE TITLE
InvalidWireTypeException when attempting to use custom Protobuf generator

### ISSUE THREAD

**Issue by Nickersoft** [bazelbuild/rules_scala#1267]
Hey folks, recently I've been attempting to use `zio-grpc` with the Bazel Scala rules, and I'm curious if there are any additional, perhaps undocumented, steps required to use custom code generators in the Scala toolchain. I posted this issue over on the `zio-grpc` repo (https://github.com/scalapb/zio-grpc/issues/255), but it sounds like it may be a case of protoc passing in bad data so I thought I'd check here too. 

Basically, I'm just pulling the sbt codegen JAR from Maven, wrapping it in a binary, then consuming it:

```python
scala_binary(
    name = "codegen",
    deps = ["@maven//:com_thesamet_scalapb_zio_grpc_zio_grpc_codegen_2_12"],
    main_class = "scalapb.zio_grpc.ZioCodeGenerator"
)

scala_proto_toolchain(
    name = "scala_proto_toolchain",
    with_grpc = True,
    code_generator = ":codegen",
    visibility = ["//visibility:public"],
)

toolchain(
    name = "scalapb_toolchain",
    toolchain = ":scala_proto_toolchain",
    toolchain_type = "@io_bazel_rules_scala//scala_proto:toolchain_type",
    visibility = ["//visibility:public"],
)
```

However, trying to compile my code I'm getting: 

```
com.google.protobuf.InvalidProtocolBufferException$InvalidWireTypeException: Protocol message tag had invalid wire type.
        at com.google.protobuf.InvalidProtocolBufferException.invalidWireType(InvalidProtocolBufferException.java:111)
        at com.google.protobuf.UnknownFieldSet$Builder.mergeFieldFrom(UnknownFieldSet.java:557)
        at com.google.protobuf.GeneratedMessageV3.parseUnknownField(GeneratedMessageV3.java:320)
        at com.google.protobuf.compiler.PluginProtos$CodeGeneratorRequest.<init>(PluginProtos.java:1092)
        at com.google.protobuf.compiler.PluginProtos$CodeGeneratorRequest.<init>(PluginProtos.java:1008)
        at com.google.protobuf.compiler.PluginProtos$CodeGeneratorRequest$1.parsePartialFrom(PluginProtos.java:2313)
        at com.google.protobuf.compiler.PluginProtos$CodeGeneratorRequest$1.parsePartialFrom(PluginProtos.java:2307)
        at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:86)
        at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:48)
        at com.google.protobuf.GeneratedMessageV3.parseWithIOException(GeneratedMessageV3.java:366)
        at com.google.protobuf.compiler.PluginProtos$CodeGeneratorRequest.parseFrom(PluginProtos.java:1467)
        at protocgen.CodeGenApp.run(CodeGenApp.scala:44)
        at protocgen.CodeGenApp.run$(CodeGenApp.scala:39)
        at scalapb.zio_grpc.ZioCodeGenerator$.run(ZioCodeGenerator.scala:21)
        at protocgen.CodeGenApp.main(CodeGenApp.scala:27)
        at protocgen.CodeGenApp.main$(CodeGenApp.scala:26)
        at scalapb.zio_grpc.ZioCodeGenerator$.main(ZioCodeGenerator.scala:21)
        at scalapb.zio_grpc.ZioCodeGenerator.main(ZioCodeGenerator.scala)
```

Also, I'm not calling the `register_toolchains()` method (or whatever it's called) from this code, because I'm defining my own (above). Not sure if that method call in WORKSPACE is still needed and maybe that's why it isn't working?

I looked through the custom loader tests contained in this repo but had a bit of trouble making sense of it. I wasn't sure what is specific to this repo and test suite and what is needed by regular apps.

Any guidance here is appreciated! I also speculated in my other ticket that maybe there is some ScalaPB dependency incompatibility happening?

**Comment by Nickersoft** [comment]
Hey @simuons! Thanks for the reply. I think that makes perfect sense... I suspected something like that might be the case. It'd be fantastic if you could write some example code for `zio-grpc` :)) I poked around the tests and got my code like.. 90% of the way there I think? 

Basically:

```python
declare_deps_provider(
    name = "scalapb_worker_deps_provider",
    deps_id = "scalapb_worker_deps",
    deps = [
        "@maven//:com_thesamet_scalapb_zio_grpc_zio_grpc_codegen_2_12",
        "@com_google_protobuf//:protobuf_java",
        "@scala_proto_rules_protoc_bridge",
        "@scala_proto_rules_scalapb_plugin",
    ],
)

scala_proto_deps_toolchain(
    name = "scala_proto_deps_toolchain_def",
    dep_providers = [
        ":scalapb_worker_deps_provider",
        "@io_bazel_rules_scala//scala_proto:scalapb_compile_deps_provider",
        "@io_bazel_rules_scala//scala_proto:scalapb_grpc_deps_provider",
    ],
)

scala_proto_toolchain(
    name = "scala_proto_toolchain",
    main_generator = "scalapb.zio_grpc.ZioCodeGenerator",
)

toolchain(
    name = "scala_proto_deps_toolchain",
    toolchain = ":scala_proto_deps_toolchain_def",
    toolchain_type = "@io_bazel_rules_scala//scala_proto:deps_toolchain_type",
)

toolchain(
    name = "scalapb_toolchain",
    toolchain = ":scala_proto_toolchain",
    toolchain_type = "@io_bazel_rules_scala//scala_proto:toolchain_type",
    visibility = ["//visibility:public"],
) 
```

and I run it with `bazel run myapp --extra_toolchains=//:scala_proto_deps_toolchain`. The only issue now is, that the code generator by `zio-grpc` obviously has a dependency on `zio` (among a few other things), and it accesses these packages via Scala `_root_`. I found https://github.com/bazelbuild/rules_scala/pull/318 but when I tried adding direct Maven dependencies to `scala_proto_library` the compiler complained. So I'm not sure how to include the deps the Zio service needs to compile.

**Comment by simuons** [comment]
@Nickersoft please take a look here https://github.com/simuons/rules-scala-scalapb-zio-grpc as an example.

**Comment by Nickersoft** [comment]
@simuons THANK YOU so much!! Super super helpful! One thing I noticed though is that your code only seems to compile with Scala 2.13... once I change it to 2.12.x (which is what I'm using), building throws:

```
bazel-out/darwin-fastbuild/bin/tmp13677820949796708458/example/example/ExampleProto.scala:10: error: Symbol 'type scala.annotation.nowarn' is missing from the classpath.
This symbol is required by ' <none>'.
Make sure that type nowarn is in your classpath and check for conflicting dependencies with `-Ylog-classpath`.
A full rebuild may help if 'GeneratedMessageCompanion.class' was compiled against an incompatible version of scala.annotation.
  lazy val messagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] =
                                   ^
one error found
Build failed
java.lang.RuntimeException: Build failed
        at io.bazel.rulesscala.scalac.ScalacWorker.compileScalaSources(ScalacWorker.java:280)
        at io.bazel.rulesscala.scalac.ScalacWorker.work(ScalacWorker.java:63)
        at io.bazel.rulesscala.worker.Worker.persistentWorkerMain(Worker.java:92)
        at io.bazel.rulesscala.worker.Worker.workerMain(Worker.java:46)
        at io.bazel.rulesscala.scalac.ScalacWorker.main(ScalacWorker.java:26)
```

I could only find documentation on this symbol for 2.13.x.. not sure if why it would be used in the code though if all artifacts and versions in WORKSPACE were changed to 2.12.

**Comment by simuons** [comment]
@Nickersoft to make it work with `scala-2.12` you need to update it to `2.12.13` (`rules_scala` brings `2.12.11`)
I have update example to build with `2.12.13`

**Comment by Nickersoft** [comment]
@simuons You are the MAN! This has helped me loads :) Managed to get my code working. I didn't realize there'd be such a large difference between two patch versions of Scala (2.12.11 -> 2.12.13), nor that supporting the latter would require so many custom toolchains. I had assumed specifying "2.12.x" as the Scala version in the config macro would just default to the latest patch version of 2.12. Anyway, closing this out, and hopefully, if someone stumbles upon this in the future it'll be of help to them!
