### PR TITLE
Upgrade Scala 2.13.12 and fix compilation issues in reporters

### LINKED ISSUE #1514: [Scala 2.13.12] Issue with scala.tools.nsc.reporters.Reporter when compiling
Seems like this [change](https://github.com/scala/scala/pull/10406/files#diff-18816e2aeb44e75b443a1aa106af41dba1cc020090b093d1c0800618dd9581ccR117) in the Scala codebase has broken compilation of `DepsTrackingReporter.java` since it introduces a new parameter (with a default value) to existing error/warning methods that Java cannot interpret seamlessly.

Here is the stacktrace I get when compiling with Scala `2.13.12`  (builds fine with `2.13.11` btw)

```
ERROR: /private/var/tmp/_bazel_sebastien/beeef587c4e635c319809c3cfc50320b/external/io_bazel_rules_scala/src/java/io/bazel/rulesscala/scalac/reporter/BUILD:5:13: Building external/io_bazel_rules_scala/src/java/io/bazel/rulesscala/scalac/reporter/libreporter.jar (2 source files) [for tool] failed: (Exit 1): java failed: error executing command (from target @io_bazel_rules_scala//src/java/io/bazel/rulesscala/scalac/reporter:reporter) external/remotejdk11_macos_aarch64/bin/java -XX:-CompactStrings '--add-exports=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED' '--add-exports=jdk.compiler/com.sun.tools.javac.main=ALL-UNNAMED' ... (remaining 18 arguments skipped)
warning: [path] bad path element "/private/var/tmp/_bazel_sebastien/beeef587c4e635c319809c3cfc50320b/execroot/platform/bazel-out/darwin_arm64-opt-exec-2B5CBBC6/bin/external/io_bazel_rules_scala_scala_compiler/io_bazel_rules_scala_scala_compiler.stamp/scala-reflect.jar": no such file or directory
warning: [path] bad path element "/private/var/tmp/_bazel_sebastien/beeef587c4e635c319809c3cfc50320b/execroot/platform/bazel-out/darwin_arm64-opt-exec-2B5CBBC6/bin/external/io_bazel_rules_scala_scala_compiler/io_bazel_rules_scala_scala_compiler.stamp/scala-library.jar": no such file or directory
external/io_bazel_rules_scala/src/java/io/bazel/rulesscala/scalac/reporter/DepsTrackingReporter.java:220: error: method warning in class Reporter cannot be applied to given types;
            reporter.warning(NoPosition$.MODULE$, strictDepsReport.toString());
                    ^
  required: Position,String,List<CodeAction>
  found: NoPosition$,String
  reason: actual and formal argument lists differ in length
external/io_bazel_rules_scala/src/java/io/bazel/rulesscala/scalac/reporter/DepsTrackingReporter.java:222: error: method error in class Reporter cannot be applied to given types;
            reporter.error(NoPosition$.MODULE$, strictDepsReport.toString());
                    ^
  required: Position,String,List<CodeAction>
  found: NoPosition$,String
  reason: actual and formal argument lists differ in length
external/io_bazel_rules_scala/src/java/io/bazel/rulesscala/scalac/reporter/DepsTrackingReporter.java:228: error: method warning in class Reporter cannot be applied to given types;
            reporter.warning(NoPosition$.MODULE$, compilerDepsReport.toString());
                    ^
  required: Position,String,List<CodeAction>
  found: NoPosition$,String
  reason: actual and formal argument lists differ in length
external/io_bazel_rules_scala/src/java/io/bazel/rulesscala/scalac/reporter/DepsTrackingReporter.java:230: error: method error in class Reporter cannot be applied to given types;
            reporter.error(NoPosition$.MODULE$, compilerDepsReport.toString());
                    ^
  required: Position,String,List<CodeAction>
  found: NoPosition$,String
  reason: actual and formal argument lists differ in length
external/io_bazel_rules_scala/src/java/io/bazel/rulesscala/scalac/reporter/DepsTrackingReporter.java:250: error: method warning in class Reporter cannot be applied to given types;
            reporter.warning(NoPosition$.MODULE$, unusedDepsReport.toString());
                    ^
  required: Position,String,List<CodeAction>
  found: NoPosition$,String
  reason: actual and formal argument lists differ in length
external/io_bazel_rules_scala/src/java/io/bazel/rulesscala/scalac/reporter/DepsTrackingReporter.java:252: error: method error in class Reporter cannot be applied to given types;
            reporter.error(NoPosition$.MODULE$, unusedDepsReport.toString());
                    ^
  required: Position,String,List<CodeAction>
  found: NoPosition$,String
  reason: actual and formal argument lists differ in length
```

I could try to take a stab at it however since all existing tests are currently based on Scala `2.13.6` and I this change would require to be targeting a specific Scala version  I would appreciate some guidance on how to approach this. Thanks !

### PR DESCRIPTION
**Pull request by scoquelin**
### Description
Bringing Scala `2.13.12` support by fixing reporters while maintaining backward compatibility with other Scala versions

Requires #1515 and #1518

### Motivation
Closes #1514

### CODE REVIEW

File: src/java/io/bazel/rulesscala/scalac/deps_tracking_reporter/after_2_13_12/DepsTrackingReporter.java [hunk 1]
```diff
@@ -0,0 +1,314 @@
...
+                    count++;
+                    unusedDepsReport
+                            .append(isWarning ? "warning: " : "error: ")
+                            .append(removeDepMessage(dep));
+                }
+                if (count > 0) {
+                    if (isWarning) {
+                        reporter.warning(NoPosition$.MODULE$, unusedDepsReport.toString(), List$.MODULE$.<CodeAction>empty());
+                    } else if (ops.unusedDependencyCheckerMode.equals("error")) {
+                       //reporter.error(NoPosition$.MODULE$, unusedDepsReport.toString(), List$.MODULE$.<CodeAction>empty());
```
Comment (scoquelin) [inline src/java/io/bazel/rulesscala/scalac/deps_tracking_reporter/after_2_13_12/DepsTrackingReporter.java:250]: So now it build fine by adding an empty Scala `List[Action]` to warning/error methods but somehow it triggers a behaviour change where now `bazel build //... --repo_env=SCALA_VERSION=2.13.12` within `test_version/test_scala_version-{timestamp}` directory  will exit and report unused dependencies...

```
DT:bazel-out/k8-fastbuild/bin/external/io_bazel_rules_scala_scala_library/io_bazel_rules_scala_scala_library.stamp/scala-library-2.13.12-stamped.jar
warning: 1 deprecation (since 2.13.0); re-run with -deprecation for details
1 warning
error: Unused dependencies:
error: Target '//:MixJavaScalaLib' (via jar: ' bazel-out/k8-fastbuild/bin/MixJavaScalaLib_java.jar ')  is specified as a dependency to //:MixJavaScalaLibBinary but isn't used, please remove it from the deps.
You can use the following buildozer command:
buildozer 'remove deps //:MixJavaScalaLib' //:MixJavaScalaLibBinary
error: Target '//:MixJavaScalaLib' (via jar: ' bazel-out/k8-fastbuild/bin/MixJavaScalaLib.jar ')  is specified as a dependency to //:MixJavaScalaLibBinary but isn't used, please remove it from the deps.
You can use the following buildozer command:
buildozer 'remove deps //:MixJavaScalaLib' //:MixJavaScalaLibBinary
Build failed
java.lang.RuntimeException: Build failed
	at io.bazel.rulesscala.scalac.ScalacWorker.compileScalaSources(ScalacWorker.java:324)
	at io.bazel.rulesscala.scalac.ScalacWorker.work(ScalacWorker.java:72)
	at io.bazel.rulesscala.worker.Worker.persistentWorkerMain(Worker.java:86)
	at io.bazel.rulesscala.worker.Worker.workerMain(Worker.java:39)
	at io.bazel.rulesscala.scalac.ScalacWorker.main(ScalacWorker.java:
```

Cannot even reproduce this behaviour with Scala  `2.13.11` and from what I can tell default is `unused_dependency_checker_mode = "off"` for both cases :thinking: Will continue to dig as it must be related to my changes...

**Comment by liucijus** [comment]
@scoquelin please rebase/resolve conflicts

File: src/java/io/bazel/rulesscala/scalac/deps_tracking_reporter/after_2_13_12/DepsTrackingReporter.java (hunk 1 above)
Comment (scoquelin) [reply src/java/io/bazel/rulesscala/scalac/deps_tracking_reporter/after_2_13_12/DepsTrackingReporter.java:250]: With Scala `2.13.12`, I think the `//third_party/dependency_analyzer` is now finding unused dependencies.

File: src/java/io/bazel/rulesscala/scalac/deps_tracking_reporter/after_2_13_12/DepsTrackingReporter.java [hunk 2]
```diff
@@ -0,0 +1,320 @@
...
+        directTargets = Arrays.stream(ops.directTargets).collect(Collectors.toSet());
+    }
+
+    private boolean isDependencyTrackingOn() {
+        return "ast-plus".equals(ops.dependencyTrackingMethod)
+                && (!"off".equals(ops.strictDepsMode) || !"off".equals(ops.unusedDependencyCheckerMode));
+    }
+
+    @Override
+    public void doReport(Position pos, String msg, Severity severity, scala.collection.immutable.List<CodeAction> actions) {
```
Comment (scoquelin) [inline src/java/io/bazel/rulesscala/scalac/deps_tracking_reporter/after_2_13_12/DepsTrackingReporter.java:81]: TLDR; After doing some troubleshooting, found out that the workaround was to override `doReport` instead of `info0` as mentioned [here](https://github.com/scala/scala/blob/v2.13.12/src/reflect/scala/reflect/internal/Reporting.scala#L103).

Long version : figured out that the `usedJars` were not populated properly in `DepsTrackingReporter` since the overridden `info0` method (responsible for building the list of user jars) didn't seem to be called. Turns out that the compiler patch that calls `inform` which in turns calls `echo` that now invokes `doReport`... so to get input about the used jars from the compiler source `doReport` needed to be overridden starting from Scala `2.13.12`...

File: src/java/io/bazel/rulesscala/scalac/deps_tracking_reporter/after_2_13_12/DepsTrackingReporter.java [hunk 3]
```diff
@@ -0,0 +1,320 @@
...
+    directTargets = Arrays.stream(ops.directTargets).collect(Collectors.toSet());
+  }
+
+  private boolean isDependencyTrackingOn() {
+    return "ast-plus".equals(ops.dependencyTrackingMethod)
+        && (!"off".equals(ops.strictDepsMode) || !"off".equals(ops.unusedDependencyCheckerMode));
+  }
+
+  @Override
+  public void doReport(Position pos, String msg, Severity severity, scala.collection.immutable.List<CodeAction> actions) {
```
Comment (scoquelin) [inline src/java/io/bazel/rulesscala/scalac/deps_tracking_reporter/after_2_13_12/DepsTrackingReporter.java:81]: TLDR; After doing some troubleshooting, found out that the workaround was to override `doReport` instead of `info0` as mentioned [here](https://github.com/scala/scala/blob/v2.13.12/src/reflect/scala/reflect/internal/Reporting.scala#L103).

Long version : figured out that the `usedJars` were not populated properly in `DepsTrackingReporter` since the overridden `info0` method (responsible for building the list of used jars) didn't seem to be called, and  that led to issues computing the actual list of unused dependencies reason why the build was failing, wrongly reporting unused dependencies whereas they were actually used.

Turns out that the compiler patch that calls `inform` which in turns calls `echo` now invokes `doReport`... so to get input about the used jars from the compiler source `doReport` now needs to be overridden starting from Scala `2.13.12`...

**Comment by scoquelin** [comment]
> @scoquelin please rebase/resolve conflicts

Will rebase again when #1518 will be merged

**Comment by scoquelin** [comment]
@liucijus @simuons rebased and tested this version on a Scala `2.13.12` codebase :heavy_check_mark: 

Will appreciate some review/feedback thanks!

**Review by liucijus — APPROVED** [review]
Thanks, @scoquelin!

**Review by simuons — APPROVED** [review]
