### ISSUE TITLE
Failing compilations succeed in Bazel

### ISSUE THREAD

**Issue by implr** [bazelbuild/rules_scala#1120]
I am trying to bazelify SpinalHDL/VexRiscV, a sbt project, with the following rule:
```
load("@io_bazel_rules_scala//scala:scala.bzl", "scala_binary", "scala_library")

scala_library(
        name = "VexRiscV",
        srcs = glob(
            ["src/main/scala/**/*.scala"],
            exclude = ["src/main/scala/demo/**/*"]
        ),
        plugins = ["@maven//:com_github_spinalhdl_spinalhdl_idsl_plugin_2_11"],
        deps = [
            "@maven//:com_github_spinalhdl_spinalhdl_core_2_11",
            "@maven//:com_github_spinalhdl_spinalhdl_sim_2_11",
            "@maven//:com_github_spinalhdl_spinalhdl_lib_2_11",
            "@maven//:com_github_spinalhdl_spinalhdl_idsl_plugin_2_11",
            "@maven//:org_yaml_snakeyaml",
            "@maven//:commons_io_commons_io",
            "@io_bazel_rules_scala_scala_compiler//:io_bazel_rules_scala_scala_compiler",
            "@io_bazel_rules_scala_scala_library//:io_bazel_rules_scala_scala_library"
            ],
)
```
Attempting to build this rule results in a lot of errors (unrelated to this issue), but **bazel reports the build as successful**:
```INFO: Analyzed target //:VexRiscV (65 packages loaded, 1292 targets configured).
INFO: Found 1 target...
INFO: From scala //:VexRiscV:
src/main/scala/spinal/lib/bus/wishbone/Wishbone.scala:53: error: Symbol 'type spinal.idslplugin.ValCallback' is missing from the classpath.
This symbol is required by 'trait spinal.core.ValCallbackRec'.
Make sure that type ValCallback is in your classpath and check for conflicting dependencies with `-Ylog-classpath`.
A full rebuild may help if 'ValCallbackRec.class' was compiled against an incompatible version of spinal.idslplugin.

...
many more errors here
...
src/main/scala/vexriscv/plugin/MmuPlugin.scala:254: error: type mismatch;
 found   : spinal.core.spinal.core.Area
 required: spinal.core.spinal.core.Area
    fenceStage plug new Area{
                    ^
Target //:VexRiscV up-to-date:
  bazel-bin/VexRiscV.jar
INFO: Elapsed time: 11.593s, Critical Path: 10.27s
INFO: 2 processes: 2 worker.
INFO: Build completed successfully, 7 total actions
```
The jar is created empty - contains just a MANIFEST.
From my basic bisecting it appears this was introduced in 2aaa7bcc104d40e.

**Comment by liucijus** [comment]
Thanks for reporting @implr. Any chances there's a public code repository which allows to reproduce this problem? 
cc @andrefmrocha, @illicitonion

**Comment by andrefmrocha** [comment]
@implr do you happen to have toggled the `enable_diagnostics_report` flag in the scala toolchain?

**Comment by implr** [comment]
I've pushed an (extremely broken) version of the repo to https://github.com/implr/VexRiscv/tree/bazelbork
`bazel build  //:VexRiscV` should fail (missing deps, among other things), but succeeds.
