### PR TITLE
Scala 2 13

### PR DESCRIPTION
**Pull request by liucijus**
Scala 2.13 support

### CODE REVIEW

**Comment by liucijus** [comment]
Blocker: Tut is unmaintained and does not work with Scala 2.13: https://github.com/tpolecat/tut/issues/263
```
[error] (run-main-0) java.lang.NoSuchMethodError: scala.tools.nsc.Settings.usejavacp()Lscala/tools/nsc/settings/AbsSettings$AbsSetting;
```
Who is using `tut`? Shall we switch to `mdoc`?

**Comment by ittaiz** [comment]
Switching to `mdoc` sounds reasonable to me given the comment of the maintainer in the link you gave above

**Comment by liucijus** [comment]
Managed to get 2.13 build passing on commit (https://github.com/bazelbuild/rules_scala/pull/1118/commits/3e5e983e4fdc462154c22bde803072da2609adca)

Reverting to 2.12 be default and leaving required changes to support 2.13.

Important changes:
- tut won't work on 2.13. Project is not maintained anymore
- commented out scalacopts https://github.com/bazelbuild/rules_scala/pull/1118/commits/d83cfeef5b5f6e1888800b417add18aa5331909c#diff-d5652869cbdde2435e06ec7400aa2623e3976c48c9c48bcf9616d83cf3eacd12
- dependency analyzer reporting is broken when the same pos is reported twice https://github.com/bazelbuild/rules_scala/pull/1118/commits/f3dc178c5377529cb0ee012df11abac726446d9c, cc @jamie5 
- had to reduce the size of for comprehension to avoid stack overflow (deleted arbitrary number of lines): https://github.com/bazelbuild/rules_scala/pull/1118/commits/3e5e983e4fdc462154c22bde803072da2609adca
- had to pass `-Xnojline` to repl tests, to avoid loading jline

**Comment by Jamie5** [comment]
I can look at the mentioned and any other dependency analyzer issues after this lands, since it sounds like it won't block the main upgrade path.

**Comment by ittaiz** [comment]
> had to reduce the size of for comprehension to avoid stack overflow (deleted arbitrary number of lines): 3e5e983

Seeing as this test is about coverage and size of generated code this change might be problematic. Can you please try to see the prod code this pushed is still covered with the lower number of for comprehension lines?

> commented out scalacopts d83cfee#diff-d5652869cbdde2435e06ec7400aa2623e3976c48c9c48bcf9616d83cf3eacd12

This can break users later on. The flags were added due to https://github.com/bazelbuild/rules_scala/pull/433 and https://github.com/bazelbuild/rules_scala/issues/432. Maybe the flags can be conditional?

**Comment by ittaiz** [comment]
Forgot 3 things:
1. Awesome!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
2. Tut => Mdoc will happen separately? Also this means that if someone uses tut and 2.12/2.11 then they should just copy our tut rule over?
3. Why is the build still failing?

**Comment by liucijus** [comment]
> > had to reduce the size of for comprehension to avoid stack overflow (deleted arbitrary number of lines): [3e5e983](https://github.com/bazelbuild/rules_scala/commit/3e5e983e4fdc462154c22bde803072da2609adca)
> 
> Seeing as this test is about coverage and size of generated code this change might be problematic. Can you please try to see the prod code this pushed is still covered with the lower number of for comprehension lines?
@ittaiz, can you explain what do you mean? 
> > commented out scalacopts [d83cfee](https://github.com/bazelbuild/rules_scala/commit/d83cfeef5b5f6e1888800b417add18aa5331909c)#diff-d5652869cbdde2435e06ec7400aa2623e3976c48c9c48bcf9616d83cf3eacd12
> 
> This can break users later on. The flags were added due to #433 and #432. Maybe the flags can be conditional?

**Comment by liucijus** [comment]
>     2. Tut => Mdoc will happen separately? Also this means that if someone uses tut and 2.12/2.11 then they should just copy our tut rule over?

I had no plans to implement mdoc support. I hope someone can send PR for this functionality - it should be trivial. 

>     3. Why is the build still failing?

Trying to find the cause, it passes locally and on my Travis config currently

**Comment by liucijus** [comment]
Done:
- scalacopts for test_reporter are different for Scala 2.13
- fixed AST analyzer reporter issue related to 2.13

@ittaiz, I think PR is ready to be merged

**Review by ittaiz — COMMENTED** [review]
I've only reviewed a third or so but sharing to get the discussion started

File: src/java/io/bazel/rulesscala/scalac/ProtoReporter.java [hunk 1]
```diff
@@ -51,29 +51,8 @@ public void writeTo(Path path) throws IOException {
   }
 
   @Override
-  public void info0(Position pos, String msg, Object severity, boolean force) {
```
[the remark this answers is not in the document]
Comment (liucijus) [reply src/java/io/bazel/rulesscala/scalac/ProtoReporter.java:54]: It's not dropped, see below - I have reduced duplication from the original implementation

File: test/coverage/D1.scala [hunk 2]
```diff
@@ -34,11 +34,6 @@ object D1 {
       _ <- l
       _ <- l
       _ <- l
-      _ <- l
```
[the remark this answers is not in the document]
Comment (liucijus) [reply test/coverage/D1.scala:37]: It's the same change

File: src/java/io/bazel/rulesscala/scalac/ScalacWorker.java [hunk 3]
```diff
@@ -250,7 +250,6 @@ private static void compileScalaSources(CompileOptions ops, String[] scalaSource
     }
 
     if (reporter.hasErrors()) {
-      reporter.printSummary();
```
[the remark this answers is not in the document]
Comment (liucijus) [reply src/java/io/bazel/rulesscala/scalac/ScalacWorker.java:253]: I think it is printing summary twice, also it's an internal API which is gone in 2.13.
Example output, I think `one error found` is repeated with this code
```
ERROR: /home/vaidas/projects/rules_scala_toolchains_proposals/src/scala/scripts/BUILD:3:14: scala //src/scala/scripts:scrooge_worker_lib failed (Exit 1)
src/scala/scripts/ScroogeWorker.scala:17: error: value asd is not a member of java.nio.file.Path
    try DeleteRecursively.run(path asd)
                                   ^
one error found
one error found

```

File: WORKSPACE [hunk 4]
```diff
@@ -170,21 +170,18 @@ load("//third_party/repositories:repositories.bzl", "repositories")
...
+    artifact_sha256 = "d7b6f800b50028c61ebed12763a100f31e900eb2f7a4af0d68f9aaaf19c24dc3",
     server_urls = MAVEN_SERVER_URLS,
 )
 
 repositories(
+    fetch_sources = False,
     for_artifact_ids = [
         # test adding a scala jar:
         "com_twitter__scalding_date",
-        # For testing that we don't include sources jars to the classpath
```
[the remark this answers is not in the document]
Comment (liucijus) [reply WORKSPACE:184]: It's a misleading leftover from repositories refactoring. Also the last supproted `org_psywerx_hairyfotr__linter` is for 2.12.

File: test/BUILD [hunk 5]
```diff
@@ -66,7 +66,6 @@ scala_binary(
 scala_library(
     name = "HelloLib",
     srcs = ["HelloLib.scala"],
-    plugins = ["@org_psywerx_hairyfotr__linter//jar"],
```
[the remark this answers is not in the document]
Comment (liucijus) [reply test/BUILD:69]: I removed unsupported plugin. Plugins are also tested with other parts of the code.

File: test/shell/test_misc.sh [hunk 6]
```diff
@@ -51,11 +51,11 @@ test_transitive_deps() {
...
-  echo "import scalarules.test._; TestUtil.foo" | bazel-bin/test/HelloLibTestRepl | grep "bar" &&
-  echo "import scalarules.test._; ScalaLibBinary.main(Array())" | bazel-bin/test/ScalaLibBinaryRepl | grep "A hui hou" &&
-  echo "import scalarules.test._; ResourcesStripScalaBinary.main(Array())" | bazel-bin/test/ResourcesStripScalaBinaryRepl | grep "More Hello"
-  echo "import scalarules.test._; A.main(Array())" | bazel-bin/test/ReplWithSources | grep "4 8 15"
+  echo "import scalarules.test._; HelloLib.printMessage(\"foo\")" | bazel-bin/test/HelloLibRepl -Xnojline | grep "foo java" &&
+  echo "import scalarules.test._; TestUtil.foo" | bazel-bin/test/HelloLibTestRepl -Xnojline | grep "bar" &&
+  echo "import scalarules.test._; ScalaLibBinary.main(Array())" | bazel-bin/test/ScalaLibBinaryRepl -Xnojline | grep "A hui hou" &&
+  echo "import scalarules.test._; ResourcesStripScalaBinary.main(Array())" | bazel-bin/test/ResourcesStripScalaBinaryRepl -Xnojline | grep "More Hello"
+  echo "import scalarules.test._; A.main(Array())" | bazel-bin/test/ReplWithSources -Xnojline | grep "4 8 15"
```
[the remark this answers is not in the document]
Comment (liucijus) [reply test/shell/test_misc.sh:58]: > had to pass -Xnojline to repl tests, to avoid loading jline
https://github.com/scala/bug/issues/11654

[the remark this answers is not in the document]
Comment (ittaiz) [reply test/shell/test_misc.sh:58]: Actually, should we be passing this arg in the production wrapper of the REPL? Not 100% sure but came to think about it when I wanted to ask you to document this but then thought- why document when we can fix. WDYT?

File: WORKSPACE (hunk 4 above)
[the remark this answers is not in the document]
Comment (ittaiz) [reply WORKSPACE:184]: So maybe I didn't notice that before (in the repositories refactoring) but from the comment it still sounds like we need to test that we don't include source jars to the classpath

**Review by ittaiz — COMMENTED** [review]
A few more things but in general super exciting! Thanks!

File: test/shell/test_misc.sh (hunk 6 above)
[the remark this answers is not in the document]
Comment (liucijus) [reply test/shell/test_misc.sh:58]: I believe it's a choice of user if they want to have jline on the classpath and use it. Probably if someone cares about repl functionallity, this should be properly solved by adding dep provider for repl first.

File: third_party/dependency_analyzer/src/test/io/bazel/rulesscala/dependencyanalyzer/AstUsedJarFinderTest.scala [hunk 7]
```diff
@@ -270,7 +270,7 @@ class AstUsedJarFinderTest extends FunSuite {
       aCode =
         s"""
            |class A(
-           |)
+           |) extends scala.annotation.Annotation
```
[the remark this answers is not in the document]
Comment (liucijus) [reply third_party/dependency_analyzer/src/test/io/bazel/rulesscala/dependencyanalyzer/AstUsedJarFinderTest.scala:273]: yes

File: test/src/main/scala/scalarules/test/scala_import/BUILD [hunk 8]
```diff
@@ -47,7 +47,6 @@ scala_library(
     name = "source_jar_not_oncp",
     testonly = True,
     srcs = ["ReferCatsImplicits.scala"],
-    # jvm_maven_import_external doesn't fetch source jars automatically
```
[the remark this answers is not in the document]
Comment (liucijus) [reply test/src/main/scala/scalarules/test/scala_import/BUILD:50]: my mistake, thanks for catching

File: test/src/main/scala/scalarules/test/scala_import/BUILD [hunk 9]
```diff
@@ -75,7 +73,10 @@ scala_specs2_junit_test(
     size = "small",
     srcs = ["ScalaImportPropagatesRuntimeDepsTest.scala"],
     suffixes = ["Test"],
-    runtime_deps = [":cats_and_guava_and_commons_lang_as_runtime_deps"],
+    runtime_deps = [
+        ":cats_and_guava_and_commons_lang_as_runtime_deps",
+        "@org_typelevel__cats_core//jar",
```
[the remark this answers is not in the document]
Comment (liucijus) [reply test/src/main/scala/scalarules/test/scala_import/BUILD]: my mistake, thanks for catching

File: test_version/version_specific_tests_dir/BUILD [hunk 10]
```diff
@@ -107,10 +107,11 @@ scala_library(
     srcs = glob(["src/main/scala/scalarules/test/mix_java_scala/*.scala"]) + glob([
         "src/main/scala/scalarules/test/mix_java_scala/*.java",
     ]),
-    scalac_jvm_flags = [
-        "-Xms1G",
-        "-Xmx4G",
-    ],
+    #    disabled due to Travis CI memory failure
+    #    scalac_jvm_flags = [
```
[the remark this answers is not in the document]
Comment (liucijus) [reply test_version/version_specific_tests_dir/BUILD:111]: Ah, didn't think it was a testcase. I don't know if there's anything equivalent in current codebase.

**Comment by liucijus** [comment]
- reverted mistakes
- found an issue while running tests with 2.13, which is fixed now with https://github.com/bazelbuild/rules_scala/pull/1118/commits/d48728e0351913b55f961cfbf9d0927570ec7056

File: WORKSPACE (hunk 4 above)
[the remark this answers is not in the document]
Comment (ittaiz) [reply WORKSPACE:184]: @liucijus not for this PR can you please check this? We either need to remove `#        "org_typelevel__cats_core"` and move the comment up or we should uncomment this and remove the `jvm_maven_import_extrernal` from above

File: test/src/main/scala/scalarules/test/scala_import/BUILD [hunk 11]
```diff
@@ -56,7 +56,6 @@ scala_import(
     name = "indirection_for_transitive_runtime_deps",
     testonly = True,
     jars = [],
-    # jvm_maven_import_external doesn't fetch source jars automatically
```
Comment (ittaiz) [inline test/src/main/scala/scalarules/test/scala_import/BUILD:59]: why remove this comment?

File: test_version/version_specific_tests_dir/BUILD (hunk 10 above)
[the remark this answers is not in the document]
Comment (ittaiz) [reply test_version/version_specific_tests_dir/BUILD:111]: Strange that it passes in the "main workspace" flow (https://github.com/bazelbuild/rules_scala/blob/e56f0dbe0cbea1de7f3993420f13867e4c069751/test/BUILD#L121).
I give up.

**Review by ittaiz — COMMENTED** [review]
LGTM. See the few small comments I made (mainly about comments 😉 ) and we'll merge today.

File: test/src/main/scala/scalarules/test/scala_import/BUILD (hunk 11 above)
Comment (liucijus) [reply test/src/main/scala/scalarules/test/scala_import/BUILD:59]: my mistake - reverting

File: test_version/version_specific_tests_dir/BUILD (hunk 10 above)
[the remark this answers is not in the document]
Comment (liucijus) [reply test_version/version_specific_tests_dir/BUILD:111]: I bet we are using more memory in some test flows

File: WORKSPACE (hunk 4 above)
[the remark this answers is not in the document]
Comment (liucijus) [reply WORKSPACE:184]: Probably it's ok to stay without this comment as it is the duplicate of https://github.com/bazelbuild/rules_scala/pull/1118/commits/1b141a9f1fce3543040aa2a8a19ab9801c9c295f

[the remark this answers is not in the document]
Comment (ittaiz) [reply WORKSPACE:184]: There are two comments here:
1. `# "org_typelevel__cats_core"` itself is commented out. You didn't move it in to the repositories but you also kept it here commented out. We need one or the other (maybe because it's only for testing it should be kept as is and just remove the comment).
2. The comment about why we need it- That relates to what you linked to and my reply is that it's sort of duplicated but in this context it's if someone wants to understand why we use cats in our repo without searching everywhere. I think it's better but I can live with it.

[the remark this answers is not in the document]
Comment (liucijus) [reply WORKSPACE:184]: 1. Are you looking at the same version? I don't see a comment `# "org_typelevel__cats_core"` line in WORKSPACE file
2. Commented

[the remark this answers is not in the document]
Comment (ittaiz) [reply WORKSPACE:184]: On master, line 183

[the remark this answers is not in the document]
Comment (liucijus) [reply WORKSPACE:184]: @ittaiz do you expect me to do anything more regarding this thread?

[the remark this answers is not in the document]
Comment (ittaiz) [reply WORKSPACE:184]: Yes. I can merge it and we'll do a followup PR just for it (a bit of a shame but I can live with it). What do you prefer?

[the remark this answers is not in the document]
Comment (liucijus) [reply WORKSPACE:184]: I prefer merge

[the remark this answers is not in the document]
Comment (ittaiz) [reply WORKSPACE:184]: Merging now. Please followup on this
